apiVersion: v1
kind: Service
metadata:
  name: api-queue-svc
  namespace: api-queue
spec:
  type: "ClusterIP"
  ports:
    - port: 80
      name: http
      targetPort: http
      protocol: TCP
  selector:
    app: api-queue-backend

